JanssenProject/jans-auth-server

Server/integrations/passport/PassportExternalAuthenticator.py
PR to fix oxAuth Issue https://github.com/GluuFederation/oxAuth/issues/1448
This fixed is already merged for https://github.com/GluuFederation/community-edition-setup/pull/718 and https://github.com/GluuFederation/oxAuth/pull/1479
Request to repo owner: Please add @christian-hawk to review PR
=> fix: update passport social script to handle provider config state problem

server/integrations/passport/PassportExternalAuthenticator.py, server/integrations/saml-passport/SamlPassportAuthenticator.py
Only Passport social and SAML script changes.
1. oxAuth issue closed https://github.com/GluuFederation/oxAuth/issues/1482
1. PR merged for oxAuth https://github.com/GluuFederation/oxAuth/pull/1483
1. PR opened for https://github.com/GluuFederation/community-edition-setup/pull/721
=> fixed: update jwt date check function in passport scripts

server/uma/sample/UmaClaimsGathering.py
https://github.com/GluuFederation/oxAuth/issues/1506
=> #1506 Modify the `claims-gathering` script so that it first tries to read claims from PCT before directing to the page to enter claims.

server/src/main/webapp/uma2/sample/claims_resolved.xhtml, server/uma/sample/UmaClaimsGathering.py
https://github.com/GluuFederation/oxAuth/issues/1506
=> #1506 - Modify the `claims-gathering` script so that it first tries to read claims from PCT before directing to the page to enter claims.

server/src/main/java/io/jans/as/server/servlet/AccountAccessConsentServlet.java
changed data to Data in line 141 for new version of obuk test
=> fix: changed case of Data for obuk

server/src/main/java/io/jans/as/server/servlet/AccountAccessConsentServlet.java
Corrected as first small letter for Brazil OB
=> fix: data and consentId spellings for BROB

model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
https://github.com/JanssenProject/jans-auth-server/issues/202
=> fix: fapi1-advanced-final failed due to checks

server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
FAPI Brazil : fapi1-advanced-final failed due to wrong checks #202
=> FAPI Brazil : fapi1-advanced-final failed due to wrong checks #202

server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java, server/src/main/java/io/jans/as/server/par/ws/rs/ParService.java, server/src/main/java/io/jans/as/server/par/ws/rs/ParValidator.java
fix: par endpoint has to reject request if request object has request_uri claim #212
=> fix: par endpoint has to reject request if request object has request_uri claim #212

client/src/main/java/io/jans/as/client/EndSessionResponse.java, server/src/main/java/io/jans/as/server/par/ws/rs/ParValidator.java
fix: avoid JSONException in validateRequestObject #221
=> fix: avoid JSONException in validateRequestObject #221

client/src/test/java/io/jans/as/client/dev/manual/MTSLClientAuthenticationMain.java, client/src/test/java/io/jans/as/client/ws/rs/TokenEncryptionHttpDeprecated.java, client/src/test/resources/testng.xml, common/src/main/java/io/jans/as/common/service/common/UserService.java, model/src/main/java/io/jans/as/model/config/Constants.java, model/src/main/java/io/jans/as/model/util/Util.java, server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/IAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/UnmodifiableAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/token/IdTokenFactory.java, server/src/main/java/io/jans/as/server/model/token/JwrService.java, server/src/main/java/io/jans/as/server/service/GrantService.java, server/src/main/java/io/jans/as/server/service/external/ExternalCibaEndUserNotificationService.java, server/src/main/java/io/jans/as/server/service/external/ExternalConsentGatheringService.java, server/src/main/java/io/jans/as/server/service/external/ExternalIntrospectionService.java, server/src/main/java/io/jans/as/server/service/external/ExternalPostAuthnService.java, server/src/main/java/io/jans/as/server/service/external/ExternalResourceOwnerPasswordCredentialsService.java, server/src/main/java/io/jans/as/server/service/external/ExternalRevokeTokenService.java, server/src/main/java/io/jans/as/server/service/external/ExternalUmaClaimsGatheringService.java, server/src/main/java/io/jans/as/server/service/external/ExternalUmaRptClaimsService.java, server/src/main/java/io/jans/as/server/service/external/ExternalUmaRptPolicyService.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java, server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
fix: fixing severe issues (sonar)
=> fix: fixing severe issues (sonar)

server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
feat: correct par implementation to conform latest changes in conformance suite
https://github.com/JanssenProject/jans-auth-server/issues/234
=> feat: correct par implementation to conform latest changes in conformance suite #234

server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java
=> fix: dcr in plain text is not processed

server/src/main/java/io/jans/as/server/model/token/ClientAssertion.java
fix: added check for par url in client_assertion
=> fix: added check for par url in client_assertion

model/src/main/java/io/jans/as/model/config/Constants.java, server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, server/src/main/java/io/jans/as/server/ciba/CIBAPushTokenDeliveryService.java, server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/IAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/UnmodifiableAuthorizationGrant.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java, server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java, server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
feat: added ability to specify refresh_token lifetime via script
https://github.com/JanssenProject/jans-auth-server/issues/230
=> feat: added ability to specify refresh_token lifetime via script

server/src/main/java/io/jans/as/server/service/CleanerTimer.java
fix: avoided ambiguous dependencies for type CacheProvider<?>
=> fix: avoided ambiguous dependencies for type CacheProvider<?>

server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
https://github.com/JanssenProject/jans-auth-server/issues/253
=> fix: pkce check has to be done after request object validation (FAPI OB)

server/src/main/java/io/jans/as/server/util/ServerUtil.java
fix: reverted changes in ServerUtil
=> fix: reverted changes in ServerUtil

persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java
feat: made UpdateToken scripts run only if it's bound to client
github.com/JanssenProject/jans-auth-server/issues/34
=> feat: made UpdateToken scripts run only if it's bound to client

client/src/main/java/io/jans/as/client/ClientAuthnEnabler.java
refactor: refactored client authn enabler
=> refactor: refactored client authn enabler

common/src/main/java/io/jans/as/common/util/RedirectUri.java
refactor: refactored redirect uri class
=> refactor: refactored redirect uri class

client/src/main/java/io/jans/as/client/util/KeyGenerator.java, server/conf/jans-config.json
feat: jwks_algorithms_supported has been updated (new algorithms have been added);
=> Extending crypto algorithms, Sub PR 3

client/src/main/java/io/jans/as/client/ClientAuthnEnabler.java, common/src/main/java/io/jans/as/common/util/RedirectUri.java
Revert commits from Nov 3 (build)
=> Revert commits from Nov 3 (build)

client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java, server/src/main/java/io/jans/as/server/model/authorize/JwtAuthorizationRequest.java
=> Revert "fix: jarm alignment for fapi brazil conformance"

client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java, server/src/main/java/io/jans/as/server/model/authorize/JwtAuthorizationRequest.java
Reverts JanssenProject/jans-auth-server#312
=> Revert "Revert "fix: jarm alignment for fapi brazil conformance""

client/src/main/java/io/jans/as/client/ClientAuthnEnabler.java, common/src/main/java/io/jans/as/common/util/RedirectUri.java
Reverts JanssenProject/jans-auth-server#311
=> Revert "Revert commits from Nov 3 (build)"

client/src/main/java/io/jans/as/client/util/KeyGenerator.java, model/src/main/java/io/jans/as/model/crypto/AbstractCryptoProvider.java, model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java, model/src/main/java/io/jans/as/model/crypto/ElevenCryptoProvider.java, model/src/main/java/io/jans/as/model/crypto/KeyFactory.java, model/src/main/java/io/jans/as/model/crypto/signature/ECDSAKeyFactory.java, model/src/main/java/io/jans/as/model/crypto/signature/ECDSAPrivateKey.java, model/src/main/java/io/jans/as/model/crypto/signature/EDDSAKeyFactory.java, model/src/main/java/io/jans/as/model/crypto/signature/EDDSAPrivateKey.java, model/src/main/java/io/jans/as/model/crypto/signature/EDDSAPublicKey.java, model/src/main/java/io/jans/as/model/crypto/signature/RSAKeyFactory.java, model/src/main/java/io/jans/as/model/crypto/signature/RSAPrivateKey.java, model/src/main/java/io/jans/as/model/crypto/signature/SignatureAlgorithm.java, model/src/main/java/io/jans/as/model/exception/CryptoProviderException.java, server/src/main/java/io/jans/as/server/service/ServerCryptoProvider.java, server/src/test/java/io/jans/as/server/comp/CrossEncryptionTest.java
=> Revert "Revert "Extending crypto algorithms, Sub PR 2""

server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/ClientCredentialsGrant.java, server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, server/src/main/java/io/jans/as/server/model/common/IAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/ImplicitGrant.java, server/src/main/java/io/jans/as/server/model/common/UnmodifiableAuthorizationGrant.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java, server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java, server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
feat: added support for new modifyRefreshToken script method.
https://github.com/JanssenProject/jans-auth-server/issues/34
=> feat: added support for new modifyRefreshToken script method.

server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java
https://github.com/JanssenProject/jans-auth-server/issues/34
=> fix: if there no scripts return true

server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, server/src/main/java/io/jans/as/server/model/common/IAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/UnmodifiableAuthorizationGrant.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java, server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java, server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, server/src/test/java/io/jans/as/server/comp/CleanerTimerTest.java
feat: added new modifyAccessToken interception method to UpdateToken script
https://github.com/JanssenProject/jans-auth-server/issues/34
=> feat: added new modifyAccessToken interception method to UpdateToken script

client/src/main/java/io/jans/as/client/util/KeyGenerator.java, model/src/main/java/io/jans/as/model/crypto/AbstractCryptoProvider.java, model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java, model/src/main/java/io/jans/as/model/crypto/ElevenCryptoProvider.java, server/src/main/java/io/jans/as/server/service/ServerCryptoProvider.java, server/src/test/java/io/jans/as/server/comp/CrossEncryptionTest.java
feat: add ability to specify key length for KeyGenerator
https://github.com/GluuFederation/oxAuth/issues/1587
=> feat: add ability to specify key length for KeyGenerator

model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, server/src/main/java/io/jans/as/server/auth/MTLSService.java, server/src/test/java/io/jans/as/server/service/MTLSServiceTest.java, server/src/test/resources/testng.xml
Issue: https://github.com/JanssenProject/jans-auth-server/issues/152
=> Added MTLS verification during client registration

server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java
feat: added support for getAccessTokenLifetimeInSeconds in update token script   #34
=> feat: added support for getAccessTokenLifetimeInSeconds in update token script   #34  

model/src/main/java/io/jans/as/model/config/adminui/AdminConf.java, model/src/main/java/io/jans/as/model/config/adminui/DynamicConfig.java, model/src/main/java/io/jans/as/model/config/adminui/RoleScopeMapping.java
https://github.com/JanssenProject/jans-auth-server/issues/327
=> Issue#327 feat: add models to read admin configuration

server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, server/src/main/java/io/jans/as/server/model/common/IAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/common/UnmodifiableAuthorizationGrant.java, server/src/main/java/io/jans/as/server/model/token/IdTokenFactory.java, server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java, server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java, server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
feat: added support for getIdTokenLifetimeInSeconds in update token script
https://github.com/JanssenProject/jans-auth-server/issues/34
=> feat: added support for getIdTokenLifetimeInSeconds in update token script

model/src/main/java/io/jans/as/model/config/adminui/DynamicConfig.java, model/src/main/java/io/jans/as/model/config/adminui/RolePermissionMapping.java
PR to address some changes in Admin-UI models
https://github.com/JanssenProject/jans-auth-server/issues/327
=> feat: add admin-ui models in AS #327

client/src/main/java/io/jans/as/client/ClientAuthnEnabler.java, model/src/main/java/io/jans/as/model/crypto/encryption/KeyEncryptionAlgorithm.java, model/src/main/java/io/jans/as/model/crypto/signature/ECDSAKeyFactory.java, model/src/main/java/io/jans/as/model/crypto/signature/EDDSAKeyFactory.java, model/src/main/java/io/jans/as/model/crypto/signature/EDDSAPrivateKey.java, model/src/main/java/io/jans/as/model/crypto/signature/EDDSAPublicKey.java, model/src/main/java/io/jans/as/model/crypto/signature/RSAKeyFactory.java, model/src/main/java/io/jans/as/model/jwk/Use.java, model/src/main/java/io/jans/as/model/jwt/DPoP.java, model/src/main/java/io/jans/as/model/token/TokenErrorResponseType.java, server/src/main/resources/oxauth.properties, server/src/main/resources/oxauth_bg.properties, server/src/main/resources/oxauth_de.properties, server/src/main/resources/oxauth_en.properties, server/src/main/resources/oxauth_es.properties, server/src/main/resources/oxauth_fr.properties, server/src/main/resources/oxauth_it.properties, server/src/main/resources/oxauth_ru.properties, server/src/main/resources/oxauth_tr.properties
=> fix: sonar fixes

server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java, server/src/main/java/io/jans/as/server/service/external/ExternalDiscoveryService.java, server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java
https://github.com/JanssenProject/jans-auth-server/issues/321
=> feat: add interception script for OpenID configuration response

client/src/main/java/io/jans/as/client/AuthorizationRequest.java, model/src/main/java/io/jans/as/model/util/Util.java
fix: corrected sonar reported bugs in client's authorization request
=> fix: corrected sonar reported bugs in client's authorization request

client/src/main/java/io/jans/as/client/AuthorizationRequest.java
fix: npe in AuthorizationRequest
=> fix: npe in AuthorizationRequest

pom.xml
fix: removed redundant property from pom
=> fix: removed redundant property from pom

client/src/main/java/io/jans/as/client/AuthorizationRequest.java
fix: bug in AuthorizationRequest
=> fix: bug in AuthorizationRequest

server/src/main/webapp/login.xhtml
https://github.com/GluuFederation/oxAuth/issues/1556
=> fix: login_hint not appearing

server/src/main/java/io/jans/as/server/service/external/ExternalApplicationSessionService.java, server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionUtils.java, server/src/main/java/io/jans/as/server/session/ws/rs/LogoutTokenFactory.java, server/src/main/java/io/jans/as/server/session/ws/rs/SessionRestWebService.java
feat(jans-auth-server): implemented new interception method for active sessions endpoint
https://github.com/JanssenProject/jans-auth-server/issues/27
=> feat(jans-auth-server): implemented new interception method for active sessions endpoint

server/src/main/java/io/jans/as/server/uma/authorization/UmaRPT.java
fix: corrected uma test failures
=> fix: corrected uma test failures
